testing-library/react-hooks-testing-library

- README.md
- package-lock.json
- package.json
- src/index.js
- test/customHook.test.js
- test/testHook.test.js
- test/useContext.test.js
- test/useEffect.test.js
- test/useMemo.test.js
- test/useReducer.test.js
- test/useRef.test.js
- test/useState.test.js
So my review found that `useHook` and `testHook` offered practically identical features.  The `testHook` implementation is simpler than what I had in `useHook` so I took that as the base for moving forward.
I made one change to `testHook` to allow the callback to take props (similar to`useHook`).  In my opinion, this offers a slightly nicer story for updating the values passed to the hook to test how the result changed when inputs changed.  It's also backwards compatible with the old `testHook` so whatever people were doing before will continue to work when migrating across.
I'm also not a big fan of the `options.wrapper` usage.  Having to wrap a context provider in order to pass the `value` to it seemed clunky in practice.  Even the tests in `react-testing-library` had to [turn off lint …
> Replace core code with testHook from react-testing-library

- .all-contributorsrc
- README.md
- index.d.ts
- package-lock.json
- package.json
- test/typescript.test.js
- test/typescript/renderHook.ts
- test/typescript/tsconfig.json
Close #7 
Introduce TypeScript type definitions :tada:
- Inspired by the typing tests in [Redux repo](https://github.com/reduxjs/redux/blob/master/test/typescript.spec.js)
> Add support for TypeScript

- .babelrc
- README.md
- package-lock.json
- package.json
- src/index.js
- test/asyncHook.test.js
- test/typescript/renderHook.ts
- typings/index.d.ts
**What**:
Provide ability to wait for hook to rerender to assist in testing asynchronous hooks (e.g. react-async's `useFetch`)
**Why**:
While asynchronous behaviour was not explicitly blocked by the library, testing it was often difficult when the internals of a hook used async patterns, but the underlying details (e.g. callback, `Promise`, etc.) were not exposed out of the hook's interface.
**How**:
The `renderHook` function now returns a `nextUpdate` function that returns a `Promise` that resolves when the hook is next rendered.  The signature and terminology is designed to work with the `async`/`await` pattern, e.g.
```js
test('something', async () => {
const { result, nextUpdate } = renderHook(() => useFetch('/api'))
expect(result.current.isLoading).toBe(true)
await nextUpdate() …
```
> Add `waitForNextUpdate` promise for testing async updates

- README.md
- src/index.js
- test/errorHook.test.js
- test/typescript/renderHook.ts
- typings/index.d.ts
**What**:
Capture errors that are thrown by hooks so they can be asserted in tests and are more visible in test failures.
**Why**:
Resolves #20 
**How**:
- Added `result.error` that returns any thrown value from the hook callback
- Changed `result.current` to be getter that can throw `result.error` if value is not valid
- Happy side-effect is that `result.current` is no `readonly` and cannot be overridden by users
**Checklist**:
I'll comment the parts I'm not sure about for review.
> Added error handling in hook callback

- src/index.js
- test/suspenseHook.test.js
**What**:
Added support for hooks that suspend during rendering.
**Why**:
We broke it when we started catching thrown values with the false assumption that they were always errors.
**How**:
1. Added a `Suspense` and `fallback` to allow the thrown promise to be handled
2. Moved the error handling into an `ErrorBoundary` to make it more "reacty"
**Checklist**:
- N/A - will make part of #19 
Fixes #27
> Add Suspense and ErrorBoundary to better support suspending from hooks

- package.json
this closes https://github.com/testing-library/react-hooks-testing-library/issues/104
> do not pin @types/react

- docs/usage/advanced-hooks.md
changed "ofter" to often
**What**:
**Why**:
**How**:
**Checklist**:
> small typo fix

- docs/usage/basic-hooks.md
Added single quotes in examples of docs
**What**:
**Why**:
**How**:
**Checklist**:
> Small typo fixes

- docs/usage/advanced-hooks.md
**What**:
I add `act` in the imports where applicable and remove `act` where it wasn't needed.
**Why**:
Missed out a couple of exports to make the code work out of the box.
**How**:
Changed the doc
**Checklist**:
> Add { act } to be part of import

- docs/api-reference.md
- src/cleanup.js
- src/index.js
- test/autoCleanup.disabled.test.js
- test/autoCleanup.noAfterEach.test.js
- test/autoCleanup.test.js
- test/cleanup.test.js
**What**:
Added cleanup functionality to unmount any rendered test components.
Resolved #76  
**Why**:
Currently, the underlying rendered test component is not necessarily unmounted at the end of a test, resulting in effects from `useEffect` and `useLayoutEffect` hanging around between tests.
**How**:
The library now exports a global `cleanup` function that will unmount any rendered hooks.  As per [testing-library/react-testing-library#430](https://github.com/testing-library/react-testing-library/pull/430) we also auto regester an `afterEach` handler in supported test frameworks (with an environment variable opt out).
**Checklist**:
> Global cleanup

- README.md
- package.json
**What**:
This adds the currently missing `dont-cleanup-after-each.js` file reference in `package.json` so that npm can pick it up and ship it within an upcoming release.
**Why**:
According to the docs (https://react-hooks-testing-library.com/reference/api#cleanup), it should be possible to set up this script via Jest config, but the file doesn't exist in the current package version (https://www.unpkg.com/browse/@testing-library/react-hooks@3.1.0/).
It also removes the redundant `README.md` and `LICENSE.md` from the `files` list as they are always included on `npm publish` (https://docs.npmjs.com/files/package.json#files).
**Checklist**:
> Include missing "dont-cleanup-after-each" script in npm package

- docs/usage/basic-hooks.md
**What**: Updated the Basic Hook docs examples to use the new testing-lib name. Also, made sure to run prettier to remove double quotes.
**Why**: I had copied an example and realized the import wasn't the new name.
**How**: More consistence documentation.
**Checklist**:
> Apply prettier formatting and switch to new testing-lib name

- docs/usage/advanced-hooks.md
**What**:
Fix documentation.
**Why**:
Fragment identifier is incorrect.
**How**:
**Checklist**:
> docs: fix fragment identifier

- docs/usage/advanced-hooks.md
- package-lock.json
- package.json
**What**:
- Upgrade the typings dependency
- Update the docs about the v3.3.0 changes of the `wrapper` option
**Why**:
- The typings dependency doesn't match the APIs
**Checklist**:
> Upgrade the typings dependency and update the docs

- docs/api-reference.md
- src/asyncUtils.js
- test/asyncHook.test.js
**What**:
Resolves #241
Resolves #393 
**Why**:
If hooks don't render the checks don't run.  This makes waiting for side effects or other changes outside of the hook's render lifecycle more difficult.
**How**:
* Replace `wait` with `waitFor`
* Introduces an `interval` option to `waitFor` and `waitForValueToChange`
* check callbacks run after interval time if no renders have occurred since last check
**Checklist**:
~I'm having some issues generating the docs to check the changes there.  There appears to be an issue with one of dependencies of `docz` but I have yet to look into it more closely.~ These seems to only be an issue locally.  The Netlify preview is generating fine 🤷‍♂️ 
~I'm also thinking about allowing the functionality to by passing a `falsy` value and using this as the …
> Add interval to async utilities to supplement post render checks

- package-lock.json
- package.json
**What**:
Update the version of dependency `@types/testing-library__react-hooks`
**Why**:
In 3.3.0, there's no type definition of `waitFor`, so in my project I have to use the deprecated `wait` instead.
**How**:
Run `npm update @types/testing-library__react-hooks`
**Checklist**:
> Update `@types/testing-library__react-hooks` dependency version

- package.json
**What**: force install eslint 7
**Why**: to avoid problem with gatsby that is using an old version
**How**:
**Checklist**:
> chore: add eslint as dep of the project

- src/core/index.ts
- src/types/index.ts
- src/types/internal.ts
**What**:
ReactHooksRenderer was not expecting arguments due to `src/pure` missing those args in the `renderhook` function
**Why**:
fixes TS errors
**How**:
**Checklist**:
> fix: ReactHooksRenderer renderHook was not expecting arguments

- src/pure.ts
- src/types/index.ts
- src/types/react.ts
- test/dom/autoCleanup.disabled.ts
- test/dom/autoCleanup.noAfterEach.ts
Changed `renderHook` in `ReactHooksRenderer` type to not use a generic for options but rather the react specific `RendererOptions`.
Moved `ReactHooksRenderer` into react specific types as all auto-detected renders are react renderers.  All modules are currently exporting both the shared types and the react types so this a non-breaking change.
**Checklist**:
> fix: Type for options in autodetected renderer was incorrectly inferring any passed type

- src/core/asyncUtils.ts
- src/core/index.ts
- src/dom/pure.ts
- src/helpers/createTestHarness.tsx
- src/helpers/promises.ts
- src/native/pure.ts
- src/server/pure.ts
**What**:
More consistency across the codebase.
**Why**:
It started with me wanting to have a named function as the result of `createRenderHook` rather than the anonymous arrow function it is returning now to improve stack traces when debugging, but the more I looked the more I noticed we had a real mix of regular functions and arrow functions through the codebase, even within the same file.  This led me down a rabbit hole of a few other things that weren't quite right, names default exports and a few variable names.
**How**:
For functions I followed the rules:
1. regular function at the top level
2. arrow function for inner functions
3. arrow functions for anonymous functions
We only had a single `default export` left in the codebase.  There has been a growing movement in the community …
> Refactor beta branch for a bit more consistency

- docs/api-reference.md
- package.json
- src/core/asyncUtils.ts
- src/dom/__tests__/asyncHook.test.ts
- src/helpers/error.ts
- src/helpers/promises.ts
- src/native/__tests__/asyncHook.test.ts
- src/server/__tests__/asyncHook.test.ts
- src/types/index.ts
**What**:
Completely refactor the async utils to be more correct and have more sensible defaults.
**Why**:
This is something I've wanted to do for a while now.  `timeout` and `interval` were both added after the async utils were originally developed, so fo backwards compatibility, we left them as defaulting to off. The catalyst for this change was to add in defaults and require people to opt out of the functionality if they wanted to.
I thought it was going to be straight forward to add the default, but when I did I found lots (most) of our async tests began failing.  I discovered that we actually had a few bugs in the implementation, particularly around overlapping `act` calls and seemingly a leaking promise that wasn't being `awaited` in some circumstances.  So I decided to build it …
> Refactor async utils

- package.json
- src/dom/__tests__/errorHook.test.ts
- src/helpers/createTestHarness.tsx
- src/helpers/promises.ts
- src/native/__tests__/errorHook.test.ts
- src/native/__tests__/resultHistory.test.ts
- src/server/__tests__/errorHook.test.ts
- src/server/__tests__/resultHistory.test.ts
- src/server/pure.ts
**What**:
Replace `try/catch` error handling with a an error boundary.
**Why**:
Fixes #308
The error boundary will catch errors thrown in `useEffect` calls as well as in the render path.
**How**:
The challenge here and why we haven't done it sooner is the excessive amount of logging produced from React when an error boundary catches and error.  I've tried many official and unofficial approaches over the years but none have worked consistently as we changed renderers and new versions of React were released. For more information, see these issues:
- https://github.com/testing-library/react-hooks-testing-library/issues/50
- https://github.com/facebook/react/issues/11098#issuecomment-412682721
- https://github.com/facebook/react/issues/15520
- https://github.com/facebook/react/issues/18841
In …
> feat: use error boundary to capture useEffect errors

- src/helpers/act.ts
- src/helpers/promises.ts
I think we removed `isPromise` thinking we didn't need it, but it rears it's head again! I also added the undefined bit just to make the act wrapper function a bit cleaner.
> refactor: reduce eslint-warnings & type changes

- src/__tests__/defaultRenderer.test.ts
- src/pure.ts
**What**:
Improve error message from our auto-detect-renderer function for users who are bundling.
**Why**:
Based on the feedback from #544
**How**:
Update the err msg & correct the test.
**Checklist**:
> [refactor] update default renderer's error message.

- .all-contributorsrc
- README.md
- docs/api-reference.md
**What**:
Fixed a couple of small grammatical errors in the `api-reference.md` doc.
**Why**:
The grammar/wording was incorrect.
**How**:
Changed the wording.
**Checklist**:
> Fix typos in api-reference.md

- docs/api-reference.md
- src/core/console.ts
- src/core/index.ts
- src/dom/__tests__/errorSuppression.disabled.test.ts
- src/dom/__tests__/errorSuppression.pure.test.ts
- src/dom/pure.ts
- src/native/__tests__/errorSuppression.disabled.test.ts
- src/native/__tests__/errorSuppression.pure.test.ts
- src/native/pure.ts
- src/pure.ts
- src/server/__tests__/errorSuppression.disabled.test.ts
- src/server/__tests__/errorSuppression.pure.test.ts
- src/server/pure.ts
- src/types/react.ts
**What**:
Add a helper to suppress the error output in the same way the automatic suppression does for users that can't use the automatic version.
Also extended the documentation around this feature to describe the requirements for automatic suppression and give instructions on how to do it manually.
**Why**:
#564 
**How**:
extracted the logic from the `beforeEach` and `afterEach` and exported them from all the modules.
**Checklist**:
> feat(console): export helper to manually suppress error output

- docs/introduction.md
Fixed a typo on the [official library website.](https://react-hooks-testing-library.com)
> Fixed a typo in the documentation

- .all-contributorsrc
- README.md
- src/pure.ts
**What**:
Tweak to make library compatible with Node 8
**Why**:
I'm using your library in an environment which _for reasons_ can only run on Node 8. 
**How**:
A minor syntax change ensures the library works in Node 8.
**Checklist**:
> fix: make library compatible with Node 8

- .all-contributorsrc
- README.md
- src/server/pure.ts
**What**:
Fix: #605
**Why**:
Before that change it was impossible to run SSR test in pure-nod eenvironment, where no DOM global objects exists.
**How**:
Div element now created only in hydration stage (also now it is a marker of hydration occurred)
**Checklist**:
> Add ability to run SSR tests in pure-node environment

- .all-contributorsrc
- README.md
- src/types/index.ts
**What**:
Correct the TypeScript definitions, so that we produce the correct return type for `act(...)` calls when `strictNullChecks` is turned off.
**Why**:
Take the following code
```ts
import { act } from '@testing-library/react-hooks'
const result = act(() => Promise.resolve())
```
With `strictNullChecks` turned on, the type of `result` is `Promise<undefined>` as you would expect.
Turn `strictNullChecks` off, and the type of `result` is now `void`.
This is particularly highlighted in my case as the project I'm working on has eslint rules that will complain if we try to await a value it thinks is not thenable.
**How**:
It seems the issue is that with `strictNullChecks`, the two overloads for `act(...)` do not have a lot of overlap so the order we specify them in doesn't matter. Without …
> fix(types) Correct overload order for act without strictNullChecks in TypeScript

- .github/workflows/validate.yml
- package.json
**What**:
Drop node 10 support
**Why**:
Fixes #621 
**How**:
Remove node `10.13` and `10` from node version matrix in github actions.
**Checklist**:
> chore: drop Node 10 support

- package.json
**What**:
Temporary fix for the Docz build.
**Why**:
It's failing due to a dependency that introduced a breaking change.
**How**:
Pin the troublesome dependency to a compatible version as suggested [here](https://github.com/doczjs/docz/issues/1635#issuecomment-888953896) by @silviuaavram.
**Checklist**:
I'll merge this one the deploy preview build passes (and the other checks of course).
As a side note, I'm half way through porting the docs to docusaurus, so this fix is simply to allow current/future PRs to pass the deploy preview checks until the the migration is complete.
> docs: fix for failing docz build

- package.json
**What**:
Pin all dev deps in `package.json`.
**Why**:
These are managed by dependabot and don't need version ranges.  I think these dependencies were added unpinned when the TS conversion was made.
**Checklist**:
I'll just merge this when all checks pass.
> chore(deps): pin all dev deps

- .all-contributorsrc
- .github/workflows/validate.yml
- README.md
- package.json
**What**:
Support running tests against multiple versions of React.
**Why**:
React 18 is coming soon and this library claims to support >=16.9
**How**:
Added a matrix of options to the github actions that will install other versions of React and run `test` against them
**Checklist**:
> Test against multiple versions of React

- .github/workflows/validate.yml
- package.json
**What**:
Refactor Build scripts.
**Why**:
After merging #663 I had an idea to remove some of the duplication between the scripts in `package.json` and `validate.yml`.
**How**:
Using env variables to set the desired version each script can simple call a base script that defines which dependencies need the set version installed.
**Checklist**:
I'll merge this once the checks pass.
> chore(ci): clean up validate scripts to remove duplication

- README.md
- docs/introduction.md
- package.json
**What**:
1. Changing type dependencies to peers deps and restricting  to <18.0
2. Add a note in README and docs about not supporting react 18 in this library
3. ~Update a bunch of dependencies that that have been waiting in other PRs for a while now~
* Reverted the dependency bumps as it broke both netlify and lint checks
**Why**:
Mostly to stop accidentally resolving type versions that will break things for people and to try to remove any confusion about why we aren't suporting React 18 yet.
**How**:
I've made the type changes a BREAKING CHANGE to be extra cautious for our users in case they need to install the dependencies themselves now, but the update should not require any code changes for anyone.
If all the build check pass for this I will just merge it without waiting for reviews.
> React 18 cleanup

- .all-contributorsrc
- README.md
- src/__tests__/ssr.test.ts
- src/server/pure.ts
**What**:
This PR adds a new test based on the work done in #607 to fix #605. Partially related to https://github.com/testing-library/react-hooks-testing-library/issues/796
**Why**:
I noticed a test wasn't added when that bug was fixed. I decided to add a test so we could prevent regressions.
**How**:
A new test was added which runs in a Node environment in Jest. 
**Checklist**:
> feat(server): add SSR test for renderHook

- README.md
**What**:
Update the React 18 upgrade docs
**Why**:
To make it easier to upgrade to React 18
**How**:
To document what the developer can do to upgrade to React 18
**Checklist**:
I tested it manually on my React project
> chore(readme): Update the React 18 upgrade docs
